apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "myapp.fullname" . }}-cronjob
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote }}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.job.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "myapp.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: cronjob
        spec:
          restartPolicy: OnFailure
          containers:
          - name: http-echo
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- if .Values.image.args }}
            args: {{ .Values.image.args | toJson }}
            {{- end }}
            ports:
            - containerPort: 5200
