apiVersion: v2
name: myapp
description: A Helm chart for running BusyBox container
type: application
version: 1.0.0
appVersion: "1.36"
author: Helm Developer
maintainers:
  - name: Helm Developer
    email: henria@gmail.com
